version: "3.0"

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: %{POSTGRES_DB}
      POSTGRES_USER: %{POSTGRES_USER}
      POSTGRES_PASSWORD: %{POSTGRES_PASSWORD}
      POSTGRES_HOST: %{POSTGRES_HOST}
      POSTGRES_PORT: %{POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgres/data
    network_mode: host

volumes:
  pg_data:
    driver: local
